project:
  type: website
  output-dir: docs

website:
  title: "Pramod Kumar"

  navbar:
    background: dark
    search: true

    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: contact.qmd
        text: Contact

    right:
      - href: reflection.qmd
        text: Reflection
      - href: appendix.qmd
        text: Appendix

  page-footer:
    left: |
      © 2026 Pramod Kumar  
      MBA – AI Applications in Business

    right: |
      Email: pknarain129@yahoo.com  
      Canada

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-navigation: true
    smooth-scroll: true